name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Identify
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ 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 }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          # your node version
          node-version: 14.21.3

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: npm run deploy
